// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static class MVC
{
    public static Testek.Web.Controllers.HomeController Home = new Testek.Web.Controllers.T4MVC_HomeController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
                      
        public static readonly string angular_bootstrap_prettify_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-bootstrap-prettify.min.js") ? Url("angular-bootstrap-prettify.min.js") : Url("angular-bootstrap-prettify.js");
                      
        public static readonly string angular_bootstrap_prettify_min_js = Url("angular-bootstrap-prettify.min.js");
        public static readonly string angular_bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-bootstrap.min.js") ? Url("angular-bootstrap.min.js") : Url("angular-bootstrap.js");
                      
        public static readonly string angular_bootstrap_min_js = Url("angular-bootstrap.min.js");
        public static readonly string angular_cookies_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-cookies.min.js") ? Url("angular-cookies.min.js") : Url("angular-cookies.js");
                      
        public static readonly string angular_cookies_min_js = Url("angular-cookies.min.js");
        public static readonly string angular_loader_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-loader.min.js") ? Url("angular-loader.min.js") : Url("angular-loader.js");
                      
        public static readonly string angular_loader_min_js = Url("angular-loader.min.js");
        public static readonly string angular_mocks_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-mocks.min.js") ? Url("angular-mocks.min.js") : Url("angular-mocks.js");
                      
        public static readonly string angular_resource_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-resource.min.js") ? Url("angular-resource.min.js") : Url("angular-resource.js");
                      
        public static readonly string angular_resource_min_js = Url("angular-resource.min.js");
        public static readonly string angular_sanitize_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-sanitize.min.js") ? Url("angular-sanitize.min.js") : Url("angular-sanitize.js");
                      
        public static readonly string angular_sanitize_min_js = Url("angular-sanitize.min.js");
        public static readonly string angular_scenario_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-scenario.min.js") ? Url("angular-scenario.min.js") : Url("angular-scenario.js");
                      
        public static readonly string angular_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular.min.js") ? Url("angular.min.js") : Url("angular.js");
                      
        public static readonly string angular_min_js = Url("angular.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class app {
            private const string URLPATH = "~/Scripts/app";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string igralecapp_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/igralecapp.min.js") ? Url("igralecapp.min.js") : Url("igralecapp.js");
                          
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class views {
                private const string URLPATH = "~/Scripts/app/views";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string main_html = Url("main.html");
            }
        
        }
    
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
                      
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class i18n {
            private const string URLPATH = "~/Scripts/i18n";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string angular_locale_am_et_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_am-et.min.js") ? Url("angular-locale_am-et.min.js") : Url("angular-locale_am-et.js");
                          
            public static readonly string angular_locale_am_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_am.min.js") ? Url("angular-locale_am.min.js") : Url("angular-locale_am.js");
                          
            public static readonly string angular_locale_ar_eg_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ar-eg.min.js") ? Url("angular-locale_ar-eg.min.js") : Url("angular-locale_ar-eg.js");
                          
            public static readonly string angular_locale_ar_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ar.min.js") ? Url("angular-locale_ar.min.js") : Url("angular-locale_ar.js");
                          
            public static readonly string angular_locale_bg_bg_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_bg-bg.min.js") ? Url("angular-locale_bg-bg.min.js") : Url("angular-locale_bg-bg.js");
                          
            public static readonly string angular_locale_bg_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_bg.min.js") ? Url("angular-locale_bg.min.js") : Url("angular-locale_bg.js");
                          
            public static readonly string angular_locale_bn_bd_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_bn-bd.min.js") ? Url("angular-locale_bn-bd.min.js") : Url("angular-locale_bn-bd.js");
                          
            public static readonly string angular_locale_bn_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_bn.min.js") ? Url("angular-locale_bn.min.js") : Url("angular-locale_bn.js");
                          
            public static readonly string angular_locale_ca_es_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ca-es.min.js") ? Url("angular-locale_ca-es.min.js") : Url("angular-locale_ca-es.js");
                          
            public static readonly string angular_locale_ca_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ca.min.js") ? Url("angular-locale_ca.min.js") : Url("angular-locale_ca.js");
                          
            public static readonly string angular_locale_cs_cz_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_cs-cz.min.js") ? Url("angular-locale_cs-cz.min.js") : Url("angular-locale_cs-cz.js");
                          
            public static readonly string angular_locale_cs_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_cs.min.js") ? Url("angular-locale_cs.min.js") : Url("angular-locale_cs.js");
                          
            public static readonly string angular_locale_da_dk_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_da-dk.min.js") ? Url("angular-locale_da-dk.min.js") : Url("angular-locale_da-dk.js");
                          
            public static readonly string angular_locale_da_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_da.min.js") ? Url("angular-locale_da.min.js") : Url("angular-locale_da.js");
                          
            public static readonly string angular_locale_de_at_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_de-at.min.js") ? Url("angular-locale_de-at.min.js") : Url("angular-locale_de-at.js");
                          
            public static readonly string angular_locale_de_be_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_de-be.min.js") ? Url("angular-locale_de-be.min.js") : Url("angular-locale_de-be.js");
                          
            public static readonly string angular_locale_de_ch_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_de-ch.min.js") ? Url("angular-locale_de-ch.min.js") : Url("angular-locale_de-ch.js");
                          
            public static readonly string angular_locale_de_de_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_de-de.min.js") ? Url("angular-locale_de-de.min.js") : Url("angular-locale_de-de.js");
                          
            public static readonly string angular_locale_de_lu_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_de-lu.min.js") ? Url("angular-locale_de-lu.min.js") : Url("angular-locale_de-lu.js");
                          
            public static readonly string angular_locale_de_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_de.min.js") ? Url("angular-locale_de.min.js") : Url("angular-locale_de.js");
                          
            public static readonly string angular_locale_el_gr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_el-gr.min.js") ? Url("angular-locale_el-gr.min.js") : Url("angular-locale_el-gr.js");
                          
            public static readonly string angular_locale_el_polyton_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_el-polyton.min.js") ? Url("angular-locale_el-polyton.min.js") : Url("angular-locale_el-polyton.js");
                          
            public static readonly string angular_locale_el_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_el.min.js") ? Url("angular-locale_el.min.js") : Url("angular-locale_el.js");
                          
            public static readonly string angular_locale_en_as_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-as.min.js") ? Url("angular-locale_en-as.min.js") : Url("angular-locale_en-as.js");
                          
            public static readonly string angular_locale_en_au_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-au.min.js") ? Url("angular-locale_en-au.min.js") : Url("angular-locale_en-au.js");
                          
            public static readonly string angular_locale_en_dsrt_us_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-dsrt-us.min.js") ? Url("angular-locale_en-dsrt-us.min.js") : Url("angular-locale_en-dsrt-us.js");
                          
            public static readonly string angular_locale_en_dsrt_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-dsrt.min.js") ? Url("angular-locale_en-dsrt.min.js") : Url("angular-locale_en-dsrt.js");
                          
            public static readonly string angular_locale_en_gb_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-gb.min.js") ? Url("angular-locale_en-gb.min.js") : Url("angular-locale_en-gb.js");
                          
            public static readonly string angular_locale_en_gu_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-gu.min.js") ? Url("angular-locale_en-gu.min.js") : Url("angular-locale_en-gu.js");
                          
            public static readonly string angular_locale_en_ie_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-ie.min.js") ? Url("angular-locale_en-ie.min.js") : Url("angular-locale_en-ie.js");
                          
            public static readonly string angular_locale_en_in_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-in.min.js") ? Url("angular-locale_en-in.min.js") : Url("angular-locale_en-in.js");
                          
            public static readonly string angular_locale_en_iso_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-iso.min.js") ? Url("angular-locale_en-iso.min.js") : Url("angular-locale_en-iso.js");
                          
            public static readonly string angular_locale_en_mh_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-mh.min.js") ? Url("angular-locale_en-mh.min.js") : Url("angular-locale_en-mh.js");
                          
            public static readonly string angular_locale_en_mp_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-mp.min.js") ? Url("angular-locale_en-mp.min.js") : Url("angular-locale_en-mp.js");
                          
            public static readonly string angular_locale_en_sg_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-sg.min.js") ? Url("angular-locale_en-sg.min.js") : Url("angular-locale_en-sg.js");
                          
            public static readonly string angular_locale_en_um_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-um.min.js") ? Url("angular-locale_en-um.min.js") : Url("angular-locale_en-um.js");
                          
            public static readonly string angular_locale_en_us_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-us.min.js") ? Url("angular-locale_en-us.min.js") : Url("angular-locale_en-us.js");
                          
            public static readonly string angular_locale_en_vi_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-vi.min.js") ? Url("angular-locale_en-vi.min.js") : Url("angular-locale_en-vi.js");
                          
            public static readonly string angular_locale_en_za_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-za.min.js") ? Url("angular-locale_en-za.min.js") : Url("angular-locale_en-za.js");
                          
            public static readonly string angular_locale_en_zz_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en-zz.min.js") ? Url("angular-locale_en-zz.min.js") : Url("angular-locale_en-zz.js");
                          
            public static readonly string angular_locale_en_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_en.min.js") ? Url("angular-locale_en.min.js") : Url("angular-locale_en.js");
                          
            public static readonly string angular_locale_es_es_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_es-es.min.js") ? Url("angular-locale_es-es.min.js") : Url("angular-locale_es-es.js");
                          
            public static readonly string angular_locale_es_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_es.min.js") ? Url("angular-locale_es.min.js") : Url("angular-locale_es.js");
                          
            public static readonly string angular_locale_et_ee_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_et-ee.min.js") ? Url("angular-locale_et-ee.min.js") : Url("angular-locale_et-ee.js");
                          
            public static readonly string angular_locale_et_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_et.min.js") ? Url("angular-locale_et.min.js") : Url("angular-locale_et.js");
                          
            public static readonly string angular_locale_eu_es_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_eu-es.min.js") ? Url("angular-locale_eu-es.min.js") : Url("angular-locale_eu-es.js");
                          
            public static readonly string angular_locale_eu_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_eu.min.js") ? Url("angular-locale_eu.min.js") : Url("angular-locale_eu.js");
                          
            public static readonly string angular_locale_fa_ir_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fa-ir.min.js") ? Url("angular-locale_fa-ir.min.js") : Url("angular-locale_fa-ir.js");
                          
            public static readonly string angular_locale_fa_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fa.min.js") ? Url("angular-locale_fa.min.js") : Url("angular-locale_fa.js");
                          
            public static readonly string angular_locale_fi_fi_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fi-fi.min.js") ? Url("angular-locale_fi-fi.min.js") : Url("angular-locale_fi-fi.js");
                          
            public static readonly string angular_locale_fi_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fi.min.js") ? Url("angular-locale_fi.min.js") : Url("angular-locale_fi.js");
                          
            public static readonly string angular_locale_fil_ph_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fil-ph.min.js") ? Url("angular-locale_fil-ph.min.js") : Url("angular-locale_fil-ph.js");
                          
            public static readonly string angular_locale_fil_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fil.min.js") ? Url("angular-locale_fil.min.js") : Url("angular-locale_fil.js");
                          
            public static readonly string angular_locale_fr_bl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fr-bl.min.js") ? Url("angular-locale_fr-bl.min.js") : Url("angular-locale_fr-bl.js");
                          
            public static readonly string angular_locale_fr_ca_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fr-ca.min.js") ? Url("angular-locale_fr-ca.min.js") : Url("angular-locale_fr-ca.js");
                          
            public static readonly string angular_locale_fr_fr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fr-fr.min.js") ? Url("angular-locale_fr-fr.min.js") : Url("angular-locale_fr-fr.js");
                          
            public static readonly string angular_locale_fr_gp_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fr-gp.min.js") ? Url("angular-locale_fr-gp.min.js") : Url("angular-locale_fr-gp.js");
                          
            public static readonly string angular_locale_fr_mc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fr-mc.min.js") ? Url("angular-locale_fr-mc.min.js") : Url("angular-locale_fr-mc.js");
                          
            public static readonly string angular_locale_fr_mf_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fr-mf.min.js") ? Url("angular-locale_fr-mf.min.js") : Url("angular-locale_fr-mf.js");
                          
            public static readonly string angular_locale_fr_mq_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fr-mq.min.js") ? Url("angular-locale_fr-mq.min.js") : Url("angular-locale_fr-mq.js");
                          
            public static readonly string angular_locale_fr_re_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fr-re.min.js") ? Url("angular-locale_fr-re.min.js") : Url("angular-locale_fr-re.js");
                          
            public static readonly string angular_locale_fr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_fr.min.js") ? Url("angular-locale_fr.min.js") : Url("angular-locale_fr.js");
                          
            public static readonly string angular_locale_gl_es_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_gl-es.min.js") ? Url("angular-locale_gl-es.min.js") : Url("angular-locale_gl-es.js");
                          
            public static readonly string angular_locale_gl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_gl.min.js") ? Url("angular-locale_gl.min.js") : Url("angular-locale_gl.js");
                          
            public static readonly string angular_locale_gsw_ch_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_gsw-ch.min.js") ? Url("angular-locale_gsw-ch.min.js") : Url("angular-locale_gsw-ch.js");
                          
            public static readonly string angular_locale_gsw_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_gsw.min.js") ? Url("angular-locale_gsw.min.js") : Url("angular-locale_gsw.js");
                          
            public static readonly string angular_locale_gu_in_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_gu-in.min.js") ? Url("angular-locale_gu-in.min.js") : Url("angular-locale_gu-in.js");
                          
            public static readonly string angular_locale_gu_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_gu.min.js") ? Url("angular-locale_gu.min.js") : Url("angular-locale_gu.js");
                          
            public static readonly string angular_locale_he_il_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_he-il.min.js") ? Url("angular-locale_he-il.min.js") : Url("angular-locale_he-il.js");
                          
            public static readonly string angular_locale_he_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_he.min.js") ? Url("angular-locale_he.min.js") : Url("angular-locale_he.js");
                          
            public static readonly string angular_locale_hi_in_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_hi-in.min.js") ? Url("angular-locale_hi-in.min.js") : Url("angular-locale_hi-in.js");
                          
            public static readonly string angular_locale_hi_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_hi.min.js") ? Url("angular-locale_hi.min.js") : Url("angular-locale_hi.js");
                          
            public static readonly string angular_locale_hr_hr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_hr-hr.min.js") ? Url("angular-locale_hr-hr.min.js") : Url("angular-locale_hr-hr.js");
                          
            public static readonly string angular_locale_hr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_hr.min.js") ? Url("angular-locale_hr.min.js") : Url("angular-locale_hr.js");
                          
            public static readonly string angular_locale_hu_hu_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_hu-hu.min.js") ? Url("angular-locale_hu-hu.min.js") : Url("angular-locale_hu-hu.js");
                          
            public static readonly string angular_locale_hu_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_hu.min.js") ? Url("angular-locale_hu.min.js") : Url("angular-locale_hu.js");
                          
            public static readonly string angular_locale_id_id_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_id-id.min.js") ? Url("angular-locale_id-id.min.js") : Url("angular-locale_id-id.js");
                          
            public static readonly string angular_locale_id_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_id.min.js") ? Url("angular-locale_id.min.js") : Url("angular-locale_id.js");
                          
            public static readonly string angular_locale_in_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_in.min.js") ? Url("angular-locale_in.min.js") : Url("angular-locale_in.js");
                          
            public static readonly string angular_locale_is_is_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_is-is.min.js") ? Url("angular-locale_is-is.min.js") : Url("angular-locale_is-is.js");
                          
            public static readonly string angular_locale_is_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_is.min.js") ? Url("angular-locale_is.min.js") : Url("angular-locale_is.js");
                          
            public static readonly string angular_locale_it_it_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_it-it.min.js") ? Url("angular-locale_it-it.min.js") : Url("angular-locale_it-it.js");
                          
            public static readonly string angular_locale_it_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_it.min.js") ? Url("angular-locale_it.min.js") : Url("angular-locale_it.js");
                          
            public static readonly string angular_locale_iw_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_iw.min.js") ? Url("angular-locale_iw.min.js") : Url("angular-locale_iw.js");
                          
            public static readonly string angular_locale_ja_jp_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ja-jp.min.js") ? Url("angular-locale_ja-jp.min.js") : Url("angular-locale_ja-jp.js");
                          
            public static readonly string angular_locale_ja_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ja.min.js") ? Url("angular-locale_ja.min.js") : Url("angular-locale_ja.js");
                          
            public static readonly string angular_locale_kn_in_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_kn-in.min.js") ? Url("angular-locale_kn-in.min.js") : Url("angular-locale_kn-in.js");
                          
            public static readonly string angular_locale_kn_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_kn.min.js") ? Url("angular-locale_kn.min.js") : Url("angular-locale_kn.js");
                          
            public static readonly string angular_locale_ko_kr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ko-kr.min.js") ? Url("angular-locale_ko-kr.min.js") : Url("angular-locale_ko-kr.js");
                          
            public static readonly string angular_locale_ko_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ko.min.js") ? Url("angular-locale_ko.min.js") : Url("angular-locale_ko.js");
                          
            public static readonly string angular_locale_ln_cd_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ln-cd.min.js") ? Url("angular-locale_ln-cd.min.js") : Url("angular-locale_ln-cd.js");
                          
            public static readonly string angular_locale_ln_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ln.min.js") ? Url("angular-locale_ln.min.js") : Url("angular-locale_ln.js");
                          
            public static readonly string angular_locale_lt_lt_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_lt-lt.min.js") ? Url("angular-locale_lt-lt.min.js") : Url("angular-locale_lt-lt.js");
                          
            public static readonly string angular_locale_lt_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_lt.min.js") ? Url("angular-locale_lt.min.js") : Url("angular-locale_lt.js");
                          
            public static readonly string angular_locale_lv_lv_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_lv-lv.min.js") ? Url("angular-locale_lv-lv.min.js") : Url("angular-locale_lv-lv.js");
                          
            public static readonly string angular_locale_lv_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_lv.min.js") ? Url("angular-locale_lv.min.js") : Url("angular-locale_lv.js");
                          
            public static readonly string angular_locale_ml_in_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ml-in.min.js") ? Url("angular-locale_ml-in.min.js") : Url("angular-locale_ml-in.js");
                          
            public static readonly string angular_locale_ml_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ml.min.js") ? Url("angular-locale_ml.min.js") : Url("angular-locale_ml.js");
                          
            public static readonly string angular_locale_mo_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_mo.min.js") ? Url("angular-locale_mo.min.js") : Url("angular-locale_mo.js");
                          
            public static readonly string angular_locale_mr_in_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_mr-in.min.js") ? Url("angular-locale_mr-in.min.js") : Url("angular-locale_mr-in.js");
                          
            public static readonly string angular_locale_mr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_mr.min.js") ? Url("angular-locale_mr.min.js") : Url("angular-locale_mr.js");
                          
            public static readonly string angular_locale_ms_my_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ms-my.min.js") ? Url("angular-locale_ms-my.min.js") : Url("angular-locale_ms-my.js");
                          
            public static readonly string angular_locale_ms_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ms.min.js") ? Url("angular-locale_ms.min.js") : Url("angular-locale_ms.js");
                          
            public static readonly string angular_locale_mt_mt_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_mt-mt.min.js") ? Url("angular-locale_mt-mt.min.js") : Url("angular-locale_mt-mt.js");
                          
            public static readonly string angular_locale_mt_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_mt.min.js") ? Url("angular-locale_mt.min.js") : Url("angular-locale_mt.js");
                          
            public static readonly string angular_locale_nl_nl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_nl-nl.min.js") ? Url("angular-locale_nl-nl.min.js") : Url("angular-locale_nl-nl.js");
                          
            public static readonly string angular_locale_nl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_nl.min.js") ? Url("angular-locale_nl.min.js") : Url("angular-locale_nl.js");
                          
            public static readonly string angular_locale_no_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_no.min.js") ? Url("angular-locale_no.min.js") : Url("angular-locale_no.js");
                          
            public static readonly string angular_locale_or_in_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_or-in.min.js") ? Url("angular-locale_or-in.min.js") : Url("angular-locale_or-in.js");
                          
            public static readonly string angular_locale_or_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_or.min.js") ? Url("angular-locale_or.min.js") : Url("angular-locale_or.js");
                          
            public static readonly string angular_locale_pl_pl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_pl-pl.min.js") ? Url("angular-locale_pl-pl.min.js") : Url("angular-locale_pl-pl.js");
                          
            public static readonly string angular_locale_pl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_pl.min.js") ? Url("angular-locale_pl.min.js") : Url("angular-locale_pl.js");
                          
            public static readonly string angular_locale_pt_br_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_pt-br.min.js") ? Url("angular-locale_pt-br.min.js") : Url("angular-locale_pt-br.js");
                          
            public static readonly string angular_locale_pt_pt_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_pt-pt.min.js") ? Url("angular-locale_pt-pt.min.js") : Url("angular-locale_pt-pt.js");
                          
            public static readonly string angular_locale_pt_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_pt.min.js") ? Url("angular-locale_pt.min.js") : Url("angular-locale_pt.js");
                          
            public static readonly string angular_locale_ro_ro_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ro-ro.min.js") ? Url("angular-locale_ro-ro.min.js") : Url("angular-locale_ro-ro.js");
                          
            public static readonly string angular_locale_ro_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ro.min.js") ? Url("angular-locale_ro.min.js") : Url("angular-locale_ro.js");
                          
            public static readonly string angular_locale_ru_ru_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ru-ru.min.js") ? Url("angular-locale_ru-ru.min.js") : Url("angular-locale_ru-ru.js");
                          
            public static readonly string angular_locale_ru_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ru.min.js") ? Url("angular-locale_ru.min.js") : Url("angular-locale_ru.js");
                          
            public static readonly string angular_locale_sk_sk_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_sk-sk.min.js") ? Url("angular-locale_sk-sk.min.js") : Url("angular-locale_sk-sk.js");
                          
            public static readonly string angular_locale_sk_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_sk.min.js") ? Url("angular-locale_sk.min.js") : Url("angular-locale_sk.js");
                          
            public static readonly string angular_locale_sl_si_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_sl-si.min.js") ? Url("angular-locale_sl-si.min.js") : Url("angular-locale_sl-si.js");
                          
            public static readonly string angular_locale_sl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_sl.min.js") ? Url("angular-locale_sl.min.js") : Url("angular-locale_sl.js");
                          
            public static readonly string angular_locale_sq_al_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_sq-al.min.js") ? Url("angular-locale_sq-al.min.js") : Url("angular-locale_sq-al.js");
                          
            public static readonly string angular_locale_sq_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_sq.min.js") ? Url("angular-locale_sq.min.js") : Url("angular-locale_sq.js");
                          
            public static readonly string angular_locale_sr_cyrl_rs_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_sr-cyrl-rs.min.js") ? Url("angular-locale_sr-cyrl-rs.min.js") : Url("angular-locale_sr-cyrl-rs.js");
                          
            public static readonly string angular_locale_sr_latn_rs_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_sr-latn-rs.min.js") ? Url("angular-locale_sr-latn-rs.min.js") : Url("angular-locale_sr-latn-rs.js");
                          
            public static readonly string angular_locale_sr_rs_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_sr-rs.min.js") ? Url("angular-locale_sr-rs.min.js") : Url("angular-locale_sr-rs.js");
                          
            public static readonly string angular_locale_sr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_sr.min.js") ? Url("angular-locale_sr.min.js") : Url("angular-locale_sr.js");
                          
            public static readonly string angular_locale_sv_se_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_sv-se.min.js") ? Url("angular-locale_sv-se.min.js") : Url("angular-locale_sv-se.js");
                          
            public static readonly string angular_locale_sv_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_sv.min.js") ? Url("angular-locale_sv.min.js") : Url("angular-locale_sv.js");
                          
            public static readonly string angular_locale_sw_tz_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_sw-tz.min.js") ? Url("angular-locale_sw-tz.min.js") : Url("angular-locale_sw-tz.js");
                          
            public static readonly string angular_locale_sw_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_sw.min.js") ? Url("angular-locale_sw.min.js") : Url("angular-locale_sw.js");
                          
            public static readonly string angular_locale_ta_in_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ta-in.min.js") ? Url("angular-locale_ta-in.min.js") : Url("angular-locale_ta-in.js");
                          
            public static readonly string angular_locale_ta_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ta.min.js") ? Url("angular-locale_ta.min.js") : Url("angular-locale_ta.js");
                          
            public static readonly string angular_locale_te_in_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_te-in.min.js") ? Url("angular-locale_te-in.min.js") : Url("angular-locale_te-in.js");
                          
            public static readonly string angular_locale_te_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_te.min.js") ? Url("angular-locale_te.min.js") : Url("angular-locale_te.js");
                          
            public static readonly string angular_locale_th_th_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_th-th.min.js") ? Url("angular-locale_th-th.min.js") : Url("angular-locale_th-th.js");
                          
            public static readonly string angular_locale_th_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_th.min.js") ? Url("angular-locale_th.min.js") : Url("angular-locale_th.js");
                          
            public static readonly string angular_locale_tl_ph_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_tl-ph.min.js") ? Url("angular-locale_tl-ph.min.js") : Url("angular-locale_tl-ph.js");
                          
            public static readonly string angular_locale_tl_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_tl.min.js") ? Url("angular-locale_tl.min.js") : Url("angular-locale_tl.js");
                          
            public static readonly string angular_locale_tr_tr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_tr-tr.min.js") ? Url("angular-locale_tr-tr.min.js") : Url("angular-locale_tr-tr.js");
                          
            public static readonly string angular_locale_tr_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_tr.min.js") ? Url("angular-locale_tr.min.js") : Url("angular-locale_tr.js");
                          
            public static readonly string angular_locale_uk_ua_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_uk-ua.min.js") ? Url("angular-locale_uk-ua.min.js") : Url("angular-locale_uk-ua.js");
                          
            public static readonly string angular_locale_uk_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_uk.min.js") ? Url("angular-locale_uk.min.js") : Url("angular-locale_uk.js");
                          
            public static readonly string angular_locale_ur_pk_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ur-pk.min.js") ? Url("angular-locale_ur-pk.min.js") : Url("angular-locale_ur-pk.js");
                          
            public static readonly string angular_locale_ur_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_ur.min.js") ? Url("angular-locale_ur.min.js") : Url("angular-locale_ur.js");
                          
            public static readonly string angular_locale_vi_vn_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_vi-vn.min.js") ? Url("angular-locale_vi-vn.min.js") : Url("angular-locale_vi-vn.js");
                          
            public static readonly string angular_locale_vi_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_vi.min.js") ? Url("angular-locale_vi.min.js") : Url("angular-locale_vi.js");
                          
            public static readonly string angular_locale_zh_cn_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_zh-cn.min.js") ? Url("angular-locale_zh-cn.min.js") : Url("angular-locale_zh-cn.js");
                          
            public static readonly string angular_locale_zh_hans_cn_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_zh-hans-cn.min.js") ? Url("angular-locale_zh-hans-cn.min.js") : Url("angular-locale_zh-hans-cn.js");
                          
            public static readonly string angular_locale_zh_hans_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_zh-hans.min.js") ? Url("angular-locale_zh-hans.min.js") : Url("angular-locale_zh-hans.js");
                          
            public static readonly string angular_locale_zh_hk_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_zh-hk.min.js") ? Url("angular-locale_zh-hk.min.js") : Url("angular-locale_zh-hk.js");
                          
            public static readonly string angular_locale_zh_tw_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_zh-tw.min.js") ? Url("angular-locale_zh-tw.min.js") : Url("angular-locale_zh-tw.js");
                          
            public static readonly string angular_locale_zh_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/angular-locale_zh.min.js") ? Url("angular-locale_zh.min.js") : Url("angular-locale_zh.js");
                          
        }
    
        public static readonly string jquery_1_8_3_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.8.3.intellisense.min.js") ? Url("jquery-1.8.3.intellisense.min.js") : Url("jquery-1.8.3.intellisense.js");
                      
        public static readonly string jquery_1_8_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.8.3.min.js") ? Url("jquery-1.8.3.min.js") : Url("jquery-1.8.3.js");
                      
        public static readonly string jquery_1_8_3_min_js = Url("jquery-1.8.3.min.js");
        public static readonly string jquery_ui_1_9_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.9.2.min.js") ? Url("jquery-ui-1.9.2.min.js") : Url("jquery-ui-1.9.2.js");
                      
        public static readonly string jquery_ui_1_9_2_min_js = Url("jquery-ui-1.9.2.min.js");
        public static readonly string jquery_unobtrusive_ajax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.unobtrusive-ajax.min.js") ? Url("jquery.unobtrusive-ajax.min.js") : Url("jquery.unobtrusive-ajax.js");
                      
        public static readonly string jquery_unobtrusive_ajax_min_js = Url("jquery.unobtrusive-ajax.min.js");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
                      
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
                      
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
                      
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string jstd_scenario_adapter_config_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jstd-scenario-adapter-config.min.js") ? Url("jstd-scenario-adapter-config.min.js") : Url("jstd-scenario-adapter-config.js");
                      
        public static readonly string jstd_scenario_adapter_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jstd-scenario-adapter.min.js") ? Url("jstd-scenario-adapter.min.js") : Url("jstd-scenario-adapter.js");
                      
        public static readonly string modernizr_2_6_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.6.2.min.js") ? Url("modernizr-2.6.2.min.js") : Url("modernizr-2.6.2.js");
                      
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string bootstrap_responsive_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-responsive.min.css") ? Url("bootstrap-responsive.min.css") : Url("bootstrap-responsive.css");
             
        public static readonly string bootstrap_responsive_min_css = Url("bootstrap-responsive.min.css");
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
             
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class images {
            private const string URLPATH = "~/Content/images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string glyphicons_halflings_white_png = Url("glyphicons-halflings-white.png");
            public static readonly string glyphicons_halflings_png = Url("glyphicons-halflings.png");
        }
    
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
             
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            private const string URLPATH = "~/Content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @base {
                private const string URLPATH = "~/Content/themes/base";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/themes/base/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                    public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                    public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                    public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                    public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                    public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                    public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                    public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                    public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                    public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                    public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                    public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                    public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                }
            
                public static readonly string jquery_ui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui.min.css") ? Url("jquery-ui.min.css") : Url("jquery-ui.css");
                     
                public static readonly string jquery_ui_accordion_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.accordion.min.css") ? Url("jquery.ui.accordion.min.css") : Url("jquery.ui.accordion.css");
                     
                public static readonly string jquery_ui_all_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.all.min.css") ? Url("jquery.ui.all.min.css") : Url("jquery.ui.all.css");
                     
                public static readonly string jquery_ui_autocomplete_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.autocomplete.min.css") ? Url("jquery.ui.autocomplete.min.css") : Url("jquery.ui.autocomplete.css");
                     
                public static readonly string jquery_ui_base_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.base.min.css") ? Url("jquery.ui.base.min.css") : Url("jquery.ui.base.css");
                     
                public static readonly string jquery_ui_button_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.button.min.css") ? Url("jquery.ui.button.min.css") : Url("jquery.ui.button.css");
                     
                public static readonly string jquery_ui_core_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.core.min.css") ? Url("jquery.ui.core.min.css") : Url("jquery.ui.core.css");
                     
                public static readonly string jquery_ui_datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.datepicker.min.css") ? Url("jquery.ui.datepicker.min.css") : Url("jquery.ui.datepicker.css");
                     
                public static readonly string jquery_ui_dialog_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.dialog.min.css") ? Url("jquery.ui.dialog.min.css") : Url("jquery.ui.dialog.css");
                     
                public static readonly string jquery_ui_menu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.menu.min.css") ? Url("jquery.ui.menu.min.css") : Url("jquery.ui.menu.css");
                     
                public static readonly string jquery_ui_progressbar_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.progressbar.min.css") ? Url("jquery.ui.progressbar.min.css") : Url("jquery.ui.progressbar.css");
                     
                public static readonly string jquery_ui_resizable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.resizable.min.css") ? Url("jquery.ui.resizable.min.css") : Url("jquery.ui.resizable.css");
                     
                public static readonly string jquery_ui_selectable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.selectable.min.css") ? Url("jquery.ui.selectable.min.css") : Url("jquery.ui.selectable.css");
                     
                public static readonly string jquery_ui_slider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.slider.min.css") ? Url("jquery.ui.slider.min.css") : Url("jquery.ui.slider.css");
                     
                public static readonly string jquery_ui_spinner_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.spinner.min.css") ? Url("jquery.ui.spinner.min.css") : Url("jquery.ui.spinner.css");
                     
                public static readonly string jquery_ui_tabs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.tabs.min.css") ? Url("jquery.ui.tabs.min.css") : Url("jquery.ui.tabs.css");
                     
                public static readonly string jquery_ui_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.theme.min.css") ? Url("jquery.ui.theme.min.css") : Url("jquery.ui.theme.css");
                     
                public static readonly string jquery_ui_tooltip_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.ui.tooltip.min.css") ? Url("jquery.ui.tooltip.min.css") : Url("jquery.ui.tooltip.css");
                     
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class minified {
                    private const string URLPATH = "~/Content/themes/base/minified";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class images {
                        private const string URLPATH = "~/Content/themes/base/minified/images";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                        public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                        public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                        public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                        public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                        public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                        public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                        public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                        public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                        public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                        public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                        public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                        public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                    }
                
                    public static readonly string jquery_ui_min_css = Url("jquery-ui.min.css");
                    public static readonly string jquery_ui_accordion_min_css = Url("jquery.ui.accordion.min.css");
                    public static readonly string jquery_ui_autocomplete_min_css = Url("jquery.ui.autocomplete.min.css");
                    public static readonly string jquery_ui_button_min_css = Url("jquery.ui.button.min.css");
                    public static readonly string jquery_ui_core_min_css = Url("jquery.ui.core.min.css");
                    public static readonly string jquery_ui_datepicker_min_css = Url("jquery.ui.datepicker.min.css");
                    public static readonly string jquery_ui_dialog_min_css = Url("jquery.ui.dialog.min.css");
                    public static readonly string jquery_ui_menu_min_css = Url("jquery.ui.menu.min.css");
                    public static readonly string jquery_ui_progressbar_min_css = Url("jquery.ui.progressbar.min.css");
                    public static readonly string jquery_ui_resizable_min_css = Url("jquery.ui.resizable.min.css");
                    public static readonly string jquery_ui_selectable_min_css = Url("jquery.ui.selectable.min.css");
                    public static readonly string jquery_ui_slider_min_css = Url("jquery.ui.slider.min.css");
                    public static readonly string jquery_ui_spinner_min_css = Url("jquery.ui.spinner.min.css");
                    public static readonly string jquery_ui_tabs_min_css = Url("jquery.ui.tabs.min.css");
                    public static readonly string jquery_ui_theme_min_css = Url("jquery.ui.theme.min.css");
                    public static readonly string jquery_ui_tooltip_min_css = Url("jquery.ui.tooltip.min.css");
                }
            
            }
        
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Scripts {}
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Styles {}
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;


    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591


