//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testek.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Igralec
    {
        public int Id { get; set; }
        public string ImePriimek { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdKvaliteta { get; set; }
    
        public virtual Kvaliteta Kvaliteta { get; set; }
    }
}
